[[redirects]]
  from = "/archive"
  to = "/writing"
  status = 301

[[redirects]]
  from = "/blog"
  query = {format = ":format"} # catch "?format=RSS"
  to = "/feed.xml"
  status = 301

[[redirects]]
  from = "/blog/*"
  to = "/writing/:splat"
  status = 301

[[redirects]]
  from = "https://openmonkey.com"
  to = "https://timriley.info"
  status = 301
[[redirects]]
  from = "https://openmonkey.com/*"
  to = "https://timriley.info/:splat"
  status = 301

[[redirects]]
  from = "https://www.openmonkey.com"
  to = "https://timriley.info"
  status = 301
[[redirects]]
  from = "https://www.openmonkey.com/*"
  to = "https://timriley.info/:splat"
  status = 301
